sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache:
  - npm
  - hexo-renderer-kramed
branches:
  only:
    - master # build master branch only
install:
  - npm install hexo-renderer-pandoc --save
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public